### ISSUE TITLE
WIN10 / 64 bits: USB Device not found, check the HW connection on PC side!

### ISSUE THREAD

**Issue by ewidance** [molejar/rawHID#1]
Hi,

I've built the project on Windows 10/64 with vs 16.3.5. Unfortunately, after launch, bottom bar says in red : USB Device not found, check the HW connection on PC side!

Same when using prebuilt rawhid.exe in release tab. 

Any prereqs? Some kind of usblib? 32 bits?

**Comment by ewidance** [comment]
OK, gotit. It seems for some reason, first connection is done with hardcoded default values (device   dUsbVid= 0x1F00 / dUsbPid = 0x2012  in AppSettings.cs).

When going to Settings icon and setting up my vid/pid (2341/8036 for adruino Leonardo), device appears in device list 
![image](https://user-images.githubusercontent.com/2135006/81720632-f545bd80-947e-11ea-941f-d8c75d8cb677.png)

At least it seems there a bug, because on software opening, it should get vid/pid saved previously if available (m_usbPid  instead of dUsbPid ).

Is the software able to enumerate devices on bus?

**Comment by molejar** [comment]
Hi, The RawHID application was primarily created for mbed usb stack, therefore the default PID/VID values have been used from mbed examples. You can change it via settings button, and it will be stored in created config file. Therefore don't forget to copy also this config file if you move the executable, else you will have the default settings.
This tool is supporting only HID devices with fixed report size 64B (descriptor parser is not implemented yet). Therefore are not enumerated all founded HID devices on bus.

**Comment by ewidance** [comment]
Hi, thank ou for your answer. 64 bytes is ok for me since i'm debugging a CNC pendant, retourning few bytes. The problem seems to be at application opening, it takes only defaut vid/pid and does to take care of previously saved personnalized vid/pid.

Could be easily improved by :
```
        private void InitializeApp()
        {
            m_usb = new HIDDevice();
            m_usb.OnDeviceRemoved += usb_OnDeviceRemoved;
            m_usb.OnDeviceArrived += usb_OnDeviceArrived;
            m_usb.OnDataRecieved += usb_OnDataReceived;

            m_connList = new List<HIDInfoSet>();
            m_cmds = new List<Command>();

            try
			{
				m_settings = LoadFromFile(m_settings.GetType(), m_confName) as AppSettings;
			}
			catch
			{
				m_settings = new AppSettings();
			}

		ScanConnection();
		...
```

**Comment by molejar** [comment]
I have fixed it, can you test? Thanks
